#!/usr/bin/env python
import sys
from optparse import OptionParser
from myslow import MySlow


parser = OptionParser()

parser.add_option("-i", "--input",  dest="input",  help="Input")
parser.add_option("-t", "--thresold", dest="thresold", help="Thresold", type="int", default=0)
parser.add_option("-f", "--format", dest="format", help="Format: csv|carbon", default="csv")
parser.add_option("-o", "--output", dest="output", help="Output", default="-")

(options, args) = parser.parse_args()

if options.input == "-":
    input_ = sys.stdin
else:
    input_ = open(options.input, 'r')

if options.format == "csv":
    from myslow.output.csv import output
elif options.format == "carbon":
    from myslow.output.carbon import Carbon
    output = Carbon(options.output)


def thresold(iterator):
    for t, h, c in iterator:
        if h['Query_time'] >= options.thresold:
            yield t, h, c

for line in output(thresold(MySlow(input_))):
    print line
